config/routes.rb
Probando::Application.routes.draw do
  get 'grupos/:id' => 'artists#show', :as => "artist"
 

  get 'letras/:id' => 'songs#show', :as => "songs"

   root :to => "welcome#index"
   get 'bands(/:id)' => 'welcome#alphabet', :as => "alphabet"
   match 'developer_code' => "welcome#developer_code"

end

app/models/alphabet.rb
class Alphabet < ActiveRecord::Base

  has_many :artists

end

app/models/artist.rb
class Artist < ActiveRecord::Base

  has_many :songs
  belongs_to :alphabet

  validates_presence_of :name
  validates_uniqueness_of :name
  
  before_validation_on_create :create_permalink, :relate_alphabet

  def create_permalink
   self.permalink = name.parameterize 
  end

  def relate_alphabet
    index = 0
    index = 4 if self.name =~ /^(The |the )/
    char = self.name[index]
    character = Alphabet.find_by_name char.downcase
    self.alphabet = character
  end


  def to_param
    permalink
    #read_attribute(:permalink)
  end

end

app/models/song.rb
class Song < ActiveRecord::Base

  belongs_to :artist

  validates_presence_of :title

  before_validation_on_create :create_permalink

  def create_permalink
    self.permalink = title.parameterize 
    #IMPORTANT the title of a song can be duplicated but the name of the artist can't be.
    #self.permalink << rand(9).to_s if Song.find_by_permalink self.permalink
    self.permalink << "-#{self.artist.name}-#{rand(100)}" if Song.find_by_permalink self.permalink

  end

  def to_param
    permalink
    #read_attribute(:permalink)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :under_construction, :except => "developer_code"

  def under_construction
    
    redirect_to :controller => "welcome", :action => "developer_code", :method => "get" if session[:developer_code].nil?

  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.xml
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.xml
  def show
    @artist = Artist.find_by_permalink(params[:id])
    @songs = @artist.songs

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.xml
  #def new
  #  @artist = Artist.new

  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.xml  { render :xml => @artist }
  #  end
  #end

  # GET /artists/1/edit
  #def edit
  #  @artist = Artist.find(params[:id])
  #end

  # POST /artists
  # POST /artists.xml
  #def create
  #  @artist = Artist.new(params[:artist])

  #  respond_to do |format|
  #    if @artist.save
  #      format.html { redirect_to(@artist, :notice => 'Artist was successfully created.') }
  #      format.xml  { render :xml => @artist, :status => :created, :location => @artist }
  #    else
  #      format.html { render :action => "new" }
  #      format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
  #    end
  #  end
  #end

  # PUT /artists/1
  # PUT /artists/1.xml
  #def update
  #  @artist = Artist.find(params[:id])

  #  respond_to do |format|
  #    if @artist.update_attributes(params[:artist])
  #      format.html { redirect_to(@artist, :notice => 'Artist was successfully updated.') }
  #      format.xml  { head :ok }
  #    else
  #      format.html { render :action => "edit" }
  #      format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /artists/1
  # DELETE /artists/1.xml
  #def destroy
  #  @artist = Artist.find(params[:id])
  #  @artist.destroy

  #  respond_to do |format|
  #    format.html { redirect_to(artists_url) }
  #    format.xml  { head :ok }
  #  end
  #end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.xml
  #def index
  #  @songs = Song.all
  #
  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.xml  { render :xml => @songs }
  #  end
  #end

  # GET /songs/1
  # GET /songs/1.xml
  def show
    @song = Song.find_by_permalink(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.xml
  #def new
  #  @song = Song.new

  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.xml  { render :xml => @song }
  #  end
  #end

  # GET /songs/1/edit
  #def edit
  #  @song = Song.find(params[:id])
  #end

  # POST /songs
  # POST /songs.xml
  #def create
  #  @song = Song.new(params[:song])

  #  respond_to do |format|
  #    if @song.save
  #      format.html { redirect_to(@song, :notice => 'Song was successfully created.') }
  #      format.xml  { render :xml => @song, :status => :created, :location => @song }
  #    else
  #      format.html { render :action => "new" }
  #      format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
  #    end
  #  end
  #end

  # PUT /songs/1
  # PUT /songs/1.xml
  #def update
  #  @song = Song.find(params[:id])

  #  respond_to do |format|
  #    if @song.update_attributes(params[:song])
  #      format.html { redirect_to(@song, :notice => 'Song was successfully updated.') }
  #      format.xml  { head :ok }
  #    else
  #      format.html { render :action => "edit" }
  #      format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /songs/1
  # DELETE /songs/1.xml
  #def destroy
  #  @song = Song.find(params[:id])
  #  @song.destroy

  #  respond_to do |format|
  #    format.html { redirect_to(songs_url) }
  #    format.xml  { head :ok }
  #  end
  #end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def alphabet
    if params[:id]
      @alphabet = Alphabet.where("id = ?",params[:id])
      @artists = @alphabet[0].artists
    else
      @artists = Artist.where("alphabet_id IS NULL")
    end
  end


  def developer_code
    if request.get?
      render "developer_code", :layout => nil 
    else 
      if params[:code].eql?("cuetara15")
        session[:developer_code] = true
        redirect_to root_path
      else
        render "developer_code", :layout => nil 
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing artists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artists.each do |artist| %>
  <tr>
    <td><%= artist.name %></td>
    <td><%= artist.description %></td>
    <td><%= link_to 'Show', artist %></td>
    <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    <td><%= link_to 'Destroy', artist, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<% content_for :head_title do %>
    <% "#{@artist.name} #{I18n.t "title_page_artist"}" %> 
<% end %>
<% content_for :head_description do %>
    <% "#{I18n.t "description_page_start_artist"}#{@artist.name}#{I18n.t "description_page_end_artist"}"%> 
<% end %>
<% content_for :breadcrumbs do %>
    <%= link_to I18n.t("bc_home"), root_path%> >
    <%= link_to "#{I18n.t "bc_alphabet"}#{@artist.alphabet.name.capitalize}", alphabet_path(@artist.alphabet) if  @artist.alphabet%>
    <%= link_to  I18n.t("bc_alphabet_number"), alphabet_path(:id => nil) unless @artist.alphabet%>
    > <%= link_to @artist.name, artist_path(@artist) %>
<% end %>


<div class="lyrics">
    <div class="big_title">
        <%= content_tag :h1, "#{I18n.t("h1_artist")} #{@artist.name}" %>
    </div>
    <ul class="song_artist_list">
        <% @songs.each{ |song|  %>
            <li>  
                <%= link_to song.title, songs_path(song) %>
            </li>
        <% } %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title><%= yield :head_title %></title>
    <meta name="description" content="<%= yield :head_description %>">
    <%= stylesheet_link_tag :all %>
    <%= stylesheet_link_tag 'screen' %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "https://www.google.com/jsapi" %>
    <%= csrf_meta_tag %>
    <%= javascript_tag "google.load('search', '1');" %>


</head>
<body>


<div class="header_container">
    <div class="header">
        <div>
            <div id="logo">
            <%= link_to image_tag("logo.png"), root_path %>
            </div>
        </div>
    </div>


<div class="header_line">
    <ul>
      <li><%= I18n.t "artist_alphabet" %></h2>
      </li>
      <% alphabet = %{ a b c d e f g h i j k l m n o p q r s t u v w x y z}.split %>
      <% alphabet.each_index { |index|  %>
        <li>  
            <%= link_to alphabet[index].capitalize, alphabet_path(:id => index + 1) %>
        </li>
      <% } %>
        <li>  
            <%= link_to "0-9", alphabet_path(:id => nil) %>
        </li>
    </ul>
</div>

</div>
<div class="container_service">
    <!--div class="container_service_border_left"></div-->
    <div class="service" id="service" > 
        <div class="breadcrumbs"> <%= yield :breadcrumbs %></div>
        <%= yield %>
        <div class="breadcrumbs"> <%= yield :breadcrumbs %></div>
    </div>
    <!--div class="container_service_border_right"></div-->
</div>

<div class="bottom">
</div>
</body>
</html>

app/views/layouts/welcomee.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Probando</title>
    <%# stylesheet_link_tag :all %>
    <%= stylesheet_link_tag 'screen' %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
</head>
<body>


<div class="header_container">
    <div class="header">
        <div>
            <div id="logo">
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
            </div>
        </div>
    </div>
</div>
<div class="header_line">
    <ul>
        <li>  
            <%= link_to "Blog", root_path %>
        </li>
    </ul>
    <ul>
        <li>  
            <%= link_to "Resume", root_path%>
        </li>
    </ul>
    <ul>
        <li>  
            <%= link_to "Projects", root_path%>
        </li>
    </ul>
    <ul>
        <li>  
            <%= link_to "Targets", root_path%>
        </li>
    </ul>
    <ul>
        <li>  
            <%= link_to "Contact", root_path%>
        </li>
    </ul>
</div>
<div class="container_service">
 <div class="container_service_border_left"   ></div>
    <div class="service" > 
        <%= yield %>
    </div>
    <div class="container_service_border_right"   ></div>

    </div>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br />
    <%= f.text_field :artist_id %>
  </div>
  <div class="field">
    <%= f.label :search %><br />
    <%= f.text_field :search %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Artist</th>
    <th>Search</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.title %></td>
    <td><%= song.lyric %></td>
    <td><%= song.artist_id %></td>
    <td><%= song.permalink %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<% content_for :head_title do %>
    <% "#{@song.title} #{I18n.t "title_page_song"}" %> 
<% end %>
<% content_for :head_description do %>
    <% "#{I18n.t "description_page_start_artist"}#{@song.title} - #{@song.artist.name}"%> 
<% end %>

<% content_for :breadcrumbs do %>
    <%= link_to I18n.t("bc_home"), root_path%> >
    <%= link_to "#{I18n.t "bc_alphabet"}#{@song.artist.alphabet.name.capitalize}", alphabet_path(@song.artist.alphabet) if  @song.artist.alphabet%>
    <%= link_to  I18n.t("bc_alphabet_number"), alphabet_path(:id => nil) unless @song.artist.alphabet%>
    > <%= link_to @song.artist.name, artist_path(@song.artist) %>
    > <%= link_to @song.title, songs_path(@song) %>
<% end %>

<div class="lyrics">
    <div class="big_title">
        <%= content_tag :h1, "#{@song.title} - #{@song.artist.name}" %>
    </div>
    <div id="lyric">
        <%= sanitize @song.lyric %>
    </div>
</div>
<%# link_to 'Edit', edit_song_path(@song) %> |
<%# link_to 'Back', songs_path %>

app/views/welcome/alphabet.html.erb
<% content_for :head_title do %>
    <% "#{I18n.t "title_page_alphabet"} #{@alphabet[0].name.capitalize}" if @alphabet %> 
    <% "#{I18n.t "title_page_alphabet_number"}" unless @alphabet %> 
<% end %>
<% content_for :head_description do %>
    <% I18n.t "description_page_alphabet" %> 
<% end %>
<% content_for :breadcrumbs do %>
    <%= link_to I18n.t("bc_home"), root_path%>
<% end %>

<div class="lyrics">
    <div class="big_title">
        <%= content_tag :h1, "#{I18n.t("h1_alphabet")} #{@alphabet[0].name.capitalize}" if @alphabet%>
        <%= content_tag :h1, I18n.t("h1_alphabet_number") unless @alphabet%>
    </div>
    <ul class="song_artist_list">
        <% @artists.each{ |artist|  %>
            <li>  
                <%= link_to artist.name, artist_path(artist) %>
            </li>
        <% } %>
    </ul>
</div>

app/views/welcome/developer_code.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zipiandzape</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%# form_tag('/welcome/developer_code') do %>
<%= form_tag(developer_code_path) do %>
  <%= password_field_tag 'code' %>
  <div><%= submit_tag 'Save' %></div>
<% end %>
</body>
</html>

app/views/welcome/index.html.erb
<% content_for :head_title do %>
    <% I18n.t "title_page_welcome" %> 
<% end %>
<% content_for :head_description do %>
    <% I18n.t "description_page_welcome" %> 
<% end %>


<div style="float:left; width:350px; margin: 5px 15px; ">
   <div class="box"> 
        <div class="title">
            <h2><%= I18n.t "message_title" %></h2>
        </div>
        <p><%= I18n.t "message_text" %></h2>
    </div>
</div>
<div style="float:left; width:350px; margin: 5px 15px;">

    <div class="box"> 
        <div class="title">
            <h2><%= I18n.t "google_search_title" %></h2>
        </div>

        <% form_tag '/', {:onSubmit => 'return GoogleSearch(); return false;'} do -%>
            <%= text_field_tag 'q','', :size => 30 %>
            <%= submit_tag 'Save' %>
        <% end -%>
    </div>

    <div class="box"> 
        <div class="title">
            <h2><%= I18n.t "index_search_title" %></h2>
        </div>
        <p><%= I18n.t "index_search_text" %></h2>
        <ul id="alphabet">
                <% alphabet = %{ a b c d e f g h i j k l m n o p q r s t u v w x y z}.split %>
                <% alphabet.each_index { |index|  %>
                <li>  
                    <%= link_to alphabet[index].capitalize, alphabet_path(:id => index + 1) %>
                </li>
                <% } %>
            </ul>
    </div>
</div>